# Generated by Django 2.2.6 on 2019-10-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number1', models.IntegerField()),
                ('room_number2', models.IntegerField()),
                ('room_number3', models.IntegerField()),
                ('room_number4', models.IntegerField()),
                ('room_number5', models.IntegerField()),
                ('room_number6', models.IntegerField()),
                ('room_number7', models.IntegerField()),
                ('room_number8', models.IntegerField()),
                ('room_number9', models.IntegerField()),
                ('room_number10', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.Hotel')),
            ],
        ),
        migrations.DeleteModel(
            name='TypesOfRoom',
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.Guest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.Manager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.Hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.Room_number'),
        ),
    ]
