# Generated by Django 2.2.6 on 2019-10-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0002_auto_20191018_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='room_type_name')),
                ('room_rent', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='cancel',
        ),
        migrations.AddField(
            model_name='record',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='checkin_date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='checkout_date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.Guest'),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_number',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=101),
        ),
        migrations.DeleteModel(
            name='Room_number',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.RoomType'),
            preserve_default=False,
        ),
    ]
