# Generated by Django 2.2.6 on 2019-10-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0003_auto_20191018_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.Guest'),
        ),
    ]
