# Generated by Django 2.2.6 on 2019-10-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0004_auto_20191018_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='manager_email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_location',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_phone',
        ),
        migrations.AlterField(
            model_name='record',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.Guest'),
        ),
    ]
